Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,5 +1,8 @@
 name: Run tests
-on: [push]
+on:
+  push:
+    branches:
+      - master
 jobs:
   test:
     runs-on: ubuntu-latest
@@ -11,15 +14,20 @@ jobs:
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
-          java-version: 17 
+          java-version: 17
 
       - name: Install dependencies
         run: mvn install
 
       - name: Run tests
         id: test
-        run: mvn test
-
+        run: |
+          test_output=$(mvn test)
+          test_result=$?
+          echo "::set-output name=test-output::$test_output"
+          if [ $test_result -ne 0 ]; then
+            echo "::set-output name=tests_failed::true"
+          fi
       - name: Notify on success
         if: ${{ steps.test.outcome == 'success' }}
         uses: appleboy/telegram-action@master
@@ -28,7 +36,7 @@ jobs:
           token: ${{ secrets.TELEGRAM_TOKEN }}
           args: все ок
 
-      - name: Notify on failure 
+      - name: Notify on failure
         if: ${{ steps.test.outcome != 'success' }}
         uses: appleboy/telegram-action@master
         with:
